server:
  port: 10000

spring:
  datasource:
    url: jdbc:mysql://shengxinjun.top:3306/hhu?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: sxj
    password: sxj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: mysql